### ISSUE TITLE
After garbage collection, `ExecutableNotFoundError` for bash

### ISSUE THREAD

**Issue by ProducerMatt** [cachix/git-hooks.nix#483] opened 2024-08-13 19:14 UTC
Hi there, use git-hooks [in this flake](https://github.com/StampyAI/stampede/blob/main/flake.nix). I recently needed to reclaim disk space, so I deleted all my .direnv folders and ran `nix-collect-garbage -d`.

upon entering my directory with direnv and trying to run `git commit`, I get this error:
```
An unexpected error has occurred: ExecutableNotFoundError: Executable `/nix/store/m36d29gn5gm9bk0g7fcln1v8171hvn95-bash-5.2-p15/bin/bash` not found
Check the log at /home/matt/.cache/pre-commit/pre-commit.log
```

Log here https://clbin.com/Kpzrf

I've tried reloading direnv and directly entering `nix develop .#`. I've also deleted `.pre-commit-config.yaml` and tried `pre-commit clean`.

Running the hooks manually with `pre-commit run` works just fine.

I guess a dependency on Bash is being made but not actually declared to Nix.

EDIT: I was able to get the missing bash with `nix copy /nix/store/m36d29gn5gm9bk0g7fcln1v8171hvn95-bash-5.2-p15/`, but it's still concerning that this dependency was untracked.

**Comment by sandydoo** [comment] 2024-08-24 13:18
I think this is a duplicate of https://github.com/cachix/git-hooks.nix/issues/161.

**Closed** 2024-08-27 13:04 UTC
Labels: bug
